### ISSUE TITLE
385_1

### ISSUE THREAD

**Issue by Chu127001** [TestingEnvENV/TestEnvAtt5_1#266]
385_1

**Comment by status-open-bounty** [comment]
Current balance: 0.0 ETH
Tokens: SNT: 2.00
Contract address: [0xdde2e4fb0f35723bf5b6c3f932271f8687f3b0a9](https://ropsten.etherscan.io/address/0xdde2e4fb0f35723bf5b6c3f932271f8687f3b0a9)
![QR Code](https://testing.openbounty.status.im/qr/TestingEnvENV/TestEnvAtt5_1/bounty/266/11a748ddc6eabe9476a5efc4a2582ee516997d7e9bb5b3d3cb1a71a340bf30b3/qr.png)
Network: Testnet (Ropsten)
To claim this bounty sign up at [https://testing.openbounty.status.im](https://testing.openbounty.status.im) and make sure to update your Ethereum address in `My Payment Details` so that the bounty is correctly allocated.
To fund it, send test ETH or test ERC20/ERC223 tokens to the contract address.
